import os

from code_graph_indexer.parsing import parser as parser_module
from code_graph_indexer.providers.metadata import LocalMetadataProvider


class DummyParser(parser_module.TreeSitterRepoParser):
    pass


def test_parser_helpers(tmp_path, monkeypatch):
    monkeypatch.setattr(parser_module.TreeSitterRepoParser, "LANGUAGE_MAP", {".py": "python"})
    monkeypatch.setattr(parser_module, "get_language", lambda name: object())

    repo = tmp_path
    file_path = repo / "a.py"
    file_path.write_text("print('hi')\n")

    parser = parser_module.TreeSitterRepoParser(str(repo), metadata_provider=LocalMetadataProvider(str(repo)))

    assert parser._is_binary(b"abc\0") is True
    assert parser._is_binary(b"abc") is False

    long_line = b"x" * (parser_module.MAX_LINE_LENGTH + 1)
    assert parser._is_minified_or_generated(long_line, "a.js") is True
    assert parser._is_minified_or_generated(b"// generated by tool", "a.js") is True
    assert parser._is_minified_or_generated(b"short line", "a.js") is False

    content, error = parser._safe_read_file(str(file_path))
    assert error is None
    assert content.startswith(b"print")


def test_load_query_and_label(tmp_path, monkeypatch):
    monkeypatch.setattr(parser_module.TreeSitterRepoParser, "LANGUAGE_MAP", {".py": "python"})
    monkeypatch.setattr(parser_module, "get_language", lambda name: object())

    repo = tmp_path
    parser = parser_module.TreeSitterRepoParser(str(repo), metadata_provider=LocalMetadataProvider(str(repo)))

    query = parser._load_query_for_language("python")
    assert "(" in query

    assert parser._generate_label("role", "entry_point") == "Application Entry Point"
    assert parser._generate_label("type", "function") == "Function Definition"
    assert parser._generate_label("other", "custom") == "Custom"


def test_should_process_file_respects_filters(tmp_path, monkeypatch):
    monkeypatch.setattr(parser_module.TreeSitterRepoParser, "LANGUAGE_MAP", {".py": "python"})
    monkeypatch.setattr(parser_module, "get_language", lambda name: object())

    repo = tmp_path
    parser = parser_module.TreeSitterRepoParser(str(repo), metadata_provider=LocalMetadataProvider(str(repo)))

    assert parser._should_process_file("src/app.py") is True
    assert parser._should_process_file(".env") is False
    assert parser._should_process_file("node_modules/lib/index.js") is False
    assert parser._should_process_file("src/package-lock.json") is True


def test_safe_read_file_rejects_large_files(tmp_path, monkeypatch):
    monkeypatch.setattr(parser_module.TreeSitterRepoParser, "LANGUAGE_MAP", {".py": "python"})
    monkeypatch.setattr(parser_module, "get_language", lambda name: object())
    monkeypatch.setattr(parser_module, "MAX_FILE_SIZE_BYTES", 1)

    repo = tmp_path
    parser = parser_module.TreeSitterRepoParser(str(repo), metadata_provider=LocalMetadataProvider(str(repo)))
    file_path = repo / "big.py"
    file_path.write_bytes(b"ab")

    content, error = parser._safe_read_file(str(file_path))
    assert content is None
    assert "File too large" in error

